PLANET_MEANINGS = {
    "Sun": {
        "archetype": "Core identity, ego, vitality, life force",
        "rules": "Leo",
        "keywords": ["self-expression", "creativity", "leadership", "pride", "confidence"],
    },
    "Moon": {
        "archetype": "Emotions, instincts, subconscious, nurturing",
        "rules": "Cancer",
        "keywords": ["emotions", "intuition", "home", "mother", "security", "habits"],
    },
    "Mercury": {
        "archetype": "Communication, intellect, travel, commerce",
        "rules": ["Gemini", "Virgo"],
        "keywords": ["communication", "thinking", "writing", "learning", "adaptability"],
    },
    "Venus": {
        "archetype": "Love, beauty, values, pleasure, relationships",
        "rules": ["Taurus", "Libra"],
        "keywords": ["love", "beauty", "art", "harmony", "pleasure", "values"],
    },
    "Mars": {
        "archetype": "Action, energy, desire, ambition, courage",
        "rules": ["Aries", "Scorpio"],
        "keywords": ["action", "desire", "courage", "passion", "energy", "aggression"],
    },
    "Jupiter": {
        "archetype": "Expansion, wisdom, luck, abundance, philosophy",
        "rules": ["Sagittarius", "Pisces"],
        "keywords": ["expansion", "luck", "wisdom", "abundance", "optimism", "faith"],
    },
    "Saturn": {
        "archetype": "Discipline, responsibility, karma, structure, time",
        "rules": ["Capricorn", "Aquarius"],
        "keywords": ["discipline", "responsibility", "structure", "limitation", "karma", "mastery"],
    },
    "Uranus": {
        "archetype": "Revolution, innovation, liberation, sudden change",
        "rules": "Aquarius",
        "keywords": ["revolution", "innovation", "freedom", "disruption", "genius", "awakening"],
    },
    "Neptune": {
        "archetype": "Spirituality, illusion, dreams, compassion, dissolution",
        "rules": "Pisces",
        "keywords": ["spirituality", "dreams", "illusion", "compassion", "mysticism", "transcendence"],
    },
    "Pluto": {
        "archetype": "Transformation, power, death and rebirth, the unconscious",
        "rules": "Scorpio",
        "keywords": ["transformation", "power", "rebirth", "obsession", "depth", "regeneration"],
    },
}

SIGN_MEANINGS = {
    "Aries": {"element": "Fire", "modality": "Cardinal", "ruler": "Mars",
               "traits": "pioneering, courageous, impulsive, energetic",
               "keywords": ["initiative", "courage", "leadership", "passion"]},
    "Taurus": {"element": "Earth", "modality": "Fixed", "ruler": "Venus",
                "traits": "stable, sensual, persistent, loyal",
                "keywords": ["stability", "sensuality", "patience", "material comfort"]},
    "Gemini": {"element": "Air", "modality": "Mutable", "ruler": "Mercury",
                "traits": "curious, adaptable, communicative, witty",
                "keywords": ["communication", "curiosity", "adaptability", "intellect"]},
    "Cancer": {"element": "Water", "modality": "Cardinal", "ruler": "Moon",
                "traits": "nurturing, intuitive, protective, emotional",
                "keywords": ["nurturing", "emotion", "home", "intuition"]},
    "Leo": {"element": "Fire", "modality": "Fixed", "ruler": "Sun",
             "traits": "dramatic, proud, generous, creative",
             "keywords": ["creativity", "pride", "generosity", "leadership"]},
    "Virgo": {"element": "Earth", "modality": "Mutable", "ruler": "Mercury",
               "traits": "analytical, practical, modest, service-oriented",
               "keywords": ["analysis", "practicality", "service", "perfectionism"]},
    "Libra": {"element": "Air", "modality": "Cardinal", "ruler": "Venus",
               "traits": "harmonious, diplomatic, aesthetic, relationship-oriented",
               "keywords": ["balance", "harmony", "relationships", "justice"]},
    "Scorpio": {"element": "Water", "modality": "Fixed", "ruler": "Pluto",
                 "traits": "intense, passionate, secretive, transformative",
                 "keywords": ["transformation", "intensity", "depth", "power"]},
    "Sagittarius": {"element": "Fire", "modality": "Mutable", "ruler": "Jupiter",
                     "traits": "adventurous, optimistic, philosophical, freedom-loving",
                     "keywords": ["freedom", "adventure", "philosophy", "optimism"]},
    "Capricorn": {"element": "Earth", "modality": "Cardinal", "ruler": "Saturn",
                   "traits": "ambitious, disciplined, practical, responsible",
                   "keywords": ["ambition", "discipline", "responsibility", "achievement"]},
    "Aquarius": {"element": "Air", "modality": "Fixed", "ruler": "Uranus",
                  "traits": "innovative, humanitarian, eccentric, independent",
                  "keywords": ["innovation", "freedom", "humanity", "vision"]},
    "Pisces": {"element": "Water", "modality": "Mutable", "ruler": "Neptune",
                "traits": "compassionate, dreamy, spiritual, boundless",
                "keywords": ["spirituality", "compassion", "dreams", "transcendence"]},
}

HOUSE_MEANINGS = {
    1: {"name": "House of Self", "area": "Identity, appearance, beginnings, first impressions",
        "keywords": ["self", "identity", "appearance", "personality"]},
    2: {"name": "House of Values", "area": "Money, possessions, self-worth, material resources",
        "keywords": ["money", "possessions", "values", "self-worth"]},
    3: {"name": "House of Communication", "area": "Siblings, local travel, learning, communication",
        "keywords": ["communication", "siblings", "learning", "travel"]},
    4: {"name": "House of Home", "area": "Home, family, roots, ancestry, inner foundation",
        "keywords": ["home", "family", "roots", "mother"]},
    5: {"name": "House of Pleasure", "area": "Creativity, romance, children, play, self-expression",
        "keywords": ["creativity", "romance", "children", "joy"]},
    6: {"name": "House of Health", "area": "Work, health, service, daily routines",
        "keywords": ["health", "work", "service", "routines"]},
    7: {"name": "House of Partnerships", "area": "Marriage, partnerships, open enemies, contracts",
        "keywords": ["partnership", "marriage", "contracts", "others"]},
    8: {"name": "House of Transformation", "area": "Sex, death, transformation, shared resources",
        "keywords": ["transformation", "shared resources", "sexuality", "rebirth"]},
    9: {"name": "House of Philosophy", "area": "Higher education, travel, philosophy, religion",
        "keywords": ["philosophy", "travel", "higher education", "beliefs"]},
    10: {"name": "House of Career", "area": "Career, public life, reputation, authority",
         "keywords": ["career", "reputation", "authority", "achievement"]},
    11: {"name": "House of Community", "area": "Friends, groups, hopes, social causes",
         "keywords": ["friends", "groups", "hopes", "community"]},
    12: {"name": "House of the Unconscious", "area": "Hidden matters, spirituality, karma, isolation",
         "keywords": ["hidden", "spirituality", "karma", "solitude"]},
}

ASPECT_MEANINGS = {
    "conjunction": {"degrees": 0, "orb": 8, "nature": "Blending",
                    "meaning": "Fusion of energies; intensification; new beginnings"},
    "sextile": {"degrees": 60, "orb": 6, "nature": "Harmonious",
                "meaning": "Opportunity; easy flow of energy; talent; cooperation"},
    "square": {"degrees": 90, "orb": 8, "nature": "Challenging",
               "meaning": "Tension; conflict; motivation; challenge driving growth"},
    "trine": {"degrees": 120, "orb": 8, "nature": "Harmonious",
              "meaning": "Natural talent; ease; harmony; gifts that flow effortlessly"},
    "opposition": {"degrees": 180, "orb": 8, "nature": "Balancing",
                   "meaning": "Polarity; awareness through others; balance needed"},
    "quincunx": {"degrees": 150, "orb": 3, "nature": "Awkward",
                 "meaning": "Adjustment needed; incongruent energies requiring integration"},
}
