import { StructuredReading } from './models';

export interface AskReportInput {
  profileName: string;
  question: string;
  domain: string | null;
  intent: string | null;
  createdAt: string | null;
  contextUsed: string[];
  evidenceRefs: string[];
  profileContextRevision: number;
  profileContextAsOf: string | null;
  reading: StructuredReading | null;
  fallbackContent: string;
}

interface ReportBlock {
  kind: 'title' | 'subtitle' | 'heading' | 'body' | 'bullet' | 'source' | 'rule';
  text?: string;
}

function clean(text: string): string {
  return String(text || '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/__(.*?)__/g, '$1')
    .replace(/^\s{0,3}#{1,6}\s*/gm, '')
    .replace(/^\s*[-*]\s+/gm, '• ')
    .replace(/[ \t]+/g, ' ')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/\s+([,.;:!?])/g, '$1')
    .trim();
}

function label(value: string | null): string {
  return clean(value ?? '')
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, letter => letter.toUpperCase());
}

function sourceLabel(source: StructuredReading['technical_basis'][number]['source']): string {
  if (!source) return 'Context Engine';
  if (typeof source === 'string') return label(source);
  return [source.key, source.ref_id, source.chunk_id, source.section, source.location]
    .filter(Boolean)
    .map(value => label(String(value)))
    .join(' · ') || 'Context Engine';
}

export function askReportText(input: AskReportInput): string {
  const reading = input.reading;
  if (!reading) return clean(input.fallbackContent);
  const generated = input.createdAt ? new Date(input.createdAt).toLocaleString() : new Date().toLocaleString();

  const lines: string[] = [
    `Profile: ${clean(input.profileName) || 'Selected profile'}`,
    'SIDDHA · Your way of life guide',
    '',
    `Question: ${clean(input.question)}`,
    `Domain: ${label(input.domain) || 'Guidance'}`,
    ...(input.intent ? [`Intent: ${label(input.intent)}`] : []),
    `Confidence: ${label(reading.confidence)}`,
    '',
    'ACKNOWLEDGMENT',
    clean(reading.acknowledgment),
  ];

  lines.push('', 'INTERPRETATION', clean(reading.interpretation));
  lines.push('', 'SUMMARY AND ASSURANCE', clean(reading.summary_and_assurance));

  if (reading.guidance.practical_actions.length) {
    lines.push('', 'PRACTICAL ACTIONS');
    reading.guidance.practical_actions.forEach((action, index) => lines.push(`${index + 1}. ${clean(action)}`));
  }
  if (reading.guidance.remedies.length) {
    lines.push('', 'TRADITIONAL SUPPORTS');
    reading.guidance.remedies.forEach(remedy => {
      lines.push(`• ${clean(remedy.practice)}`);
      if (remedy.note) lines.push(`  ${clean(remedy.note)}`);
    });
  }
  if (reading.technical_basis.length) {
    lines.push('', 'TECHNICAL BASIS');
    for (const item of reading.technical_basis) {
      lines.push(`• ${clean(item.factor)}: ${clean(item.reading)}`);
      lines.push(`  Source: ${sourceLabel(item.source)}`);
    }
  }

  const provenance = [
    ...(input.contextUsed.length ? [`Context used: ${input.contextUsed.map(label).join(', ')}`] : []),
    ...(input.evidenceRefs.length ? [`Evidence references: ${input.evidenceRefs.join(', ')}`] : []),
    ...(input.profileContextRevision > 0
      ? [`Saved profile context: revision ${input.profileContextRevision}${input.profileContextAsOf ? ` as of ${input.profileContextAsOf}` : ''}`]
      : []),
  ];
  if (provenance.length) lines.push('', 'PROVENANCE', ...provenance);

  lines.push(
    '',
    'Siddha offers reflective Vedic astrology guidance. It does not replace medical, legal, financial, or other qualified professional advice.',
    '',
    `Generated by Siddha · ${generated}`,
  );
  return lines.filter((line, index) => line || lines[index - 1] !== '').join('\n').trim();
}

function reportBlocks(input: AskReportInput): ReportBlock[] {
  const reading = input.reading;
  if (!reading) return [
    { kind: 'heading', text: 'Question' },
    { kind: 'body', text: clean(input.question) },
    { kind: 'body', text: clean(input.fallbackContent) },
  ];

  const blocks: ReportBlock[] = [
    { kind: 'heading', text: 'Question' },
    { kind: 'body', text: clean(input.question) },
    { kind: 'source', text: `${label(input.domain) || 'Guidance'} · ${label(input.intent) || 'General'} · ${label(reading.confidence)} confidence` },
    { kind: 'heading', text: 'Acknowledgment' },
    { kind: 'body', text: clean(reading.acknowledgment) },
    { kind: 'heading', text: 'Interpretation' },
    { kind: 'body', text: clean(reading.interpretation) },
    { kind: 'heading', text: 'Summary and Assurance' },
    { kind: 'body', text: clean(reading.summary_and_assurance) },
  ];
  if (reading.guidance.practical_actions.length) {
    blocks.push({ kind: 'heading', text: 'Practical Actions' });
    reading.guidance.practical_actions.forEach((action, index) => blocks.push({ kind: 'bullet', text: `${index + 1}. ${clean(action)}` }));
  }
  if (reading.guidance.remedies.length) {
    blocks.push({ kind: 'heading', text: 'Traditional Supports' });
    reading.guidance.remedies.forEach(remedy => blocks.push({ kind: 'bullet', text: `${clean(remedy.practice)}${remedy.note ? ` — ${clean(remedy.note)}` : ''}` }));
  }
  if (reading.technical_basis.length) {
    blocks.push({ kind: 'heading', text: 'Technical Basis' });
    reading.technical_basis.forEach(item => {
      blocks.push({ kind: 'bullet', text: `${clean(item.factor)}: ${clean(item.reading)}` });
      blocks.push({ kind: 'source', text: `Source: ${sourceLabel(item.source)}` });
    });
  }
  const provenance = [
    input.contextUsed.length ? `Context: ${input.contextUsed.map(label).join(', ')}` : '',
    input.evidenceRefs.length ? `Evidence: ${input.evidenceRefs.join(', ')}` : '',
    input.profileContextRevision > 0 ? `Profile context revision ${input.profileContextRevision}${input.profileContextAsOf ? ` as of ${input.profileContextAsOf}` : ''}` : '',
  ].filter(Boolean);
  if (provenance.length) {
    blocks.push({ kind: 'heading', text: 'Provenance' });
    provenance.forEach(value => blocks.push({ kind: 'source', text: value }));
  }
  blocks.push(
    { kind: 'rule' },
    { kind: 'source', text: 'Reflective guidance only. Siddha does not replace qualified medical, legal, financial, or other professional advice.' },
  );
  return blocks;
}

function wrap(context: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
  const paragraphs = String(text || '').split(/\n+/).filter(Boolean);
  const lines: string[] = [];
  for (const paragraph of paragraphs) {
    const words = paragraph.split(/\s+/);
    let line = '';
    for (const word of words) {
      const candidate = line ? `${line} ${word}` : word;
      if (line && context.measureText(candidate).width > maxWidth) {
        lines.push(line);
        line = word;
      } else {
        line = candidate;
      }
    }
    if (line) lines.push(line);
  }
  return lines;
}

function bytes(value: string): Uint8Array {
  return new TextEncoder().encode(value);
}

function joinBytes(parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const joined = new Uint8Array(total);
  let offset = 0;
  parts.forEach(part => { joined.set(part, offset); offset += part.length; });
  return joined;
}

function dataUrlBytes(dataUrl: string): Uint8Array {
  const binary = atob(dataUrl.split(',')[1] ?? '');
  return Uint8Array.from(binary, char => char.charCodeAt(0));
}

function canvasPages(input: AskReportInput): HTMLCanvasElement[] {
  const width = 1240;
  const height = 1754;
  const margin = 104;
  const bottom = height - 124;
  const profileName = clean(input.profileName) || 'Selected profile';
  const generated = input.createdAt ? new Date(input.createdAt).toLocaleString() : new Date().toLocaleString();
  const pages: HTMLCanvasElement[] = [];
  let canvas!: HTMLCanvasElement;
  let context!: CanvasRenderingContext2D;
  let y = margin;

  const newPage = () => {
    canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    context = canvas.getContext('2d')!;
    context.fillStyle = '#fffdf9';
    context.fillRect(0, 0, width, height);
    context.font = '600 20px system-ui, sans-serif';
    context.fillStyle = '#332823';
    context.textAlign = 'left';
    context.fillText(profileName, margin, 65);
    context.font = '700 22px Georgia, serif';
    context.fillStyle = '#8f3f30';
    context.textAlign = 'right';
    context.fillText('SIDDHA', width - margin, 65);
    context.strokeStyle = '#dfcec4';
    context.lineWidth = 2;
    context.beginPath();
    context.moveTo(margin, 92);
    context.lineTo(width - margin, 92);
    context.stroke();
    context.textAlign = 'left';
    pages.push(canvas);
    y = 132;
  };
  newPage();

  const style = (kind: ReportBlock['kind']) => {
    const rules = {
      title: { font: '700 52px Georgia, serif', color: '#6f2f24', line: 66, before: 0, after: 4 },
      subtitle: { font: '500 24px system-ui, sans-serif', color: '#6e625b', line: 34, before: 0, after: 18 },
      heading: { font: '700 22px system-ui, sans-serif', color: '#8f3f30', line: 31, before: 30, after: 8 },
      body: { font: '400 22px Georgia, serif', color: '#241d19', line: 34, before: 0, after: 15 },
      bullet: { font: '400 21px system-ui, sans-serif', color: '#241d19', line: 32, before: 3, after: 7 },
      source: { font: '400 16px system-ui, sans-serif', color: '#756b65', line: 25, before: 0, after: 8 },
      rule: { font: '', color: '#d8c4b9', line: 1, before: 8, after: 14 },
    };
    return rules[kind];
  };

  for (const block of reportBlocks(input)) {
    const rule = style(block.kind);
    context.font = rule.font;
    const inset = block.kind === 'bullet' ? 28 : 0;
    const contentWidth = width - margin * 2 - inset;
    const lines = block.kind === 'rule' ? [] : wrap(context, block.text ?? '', contentWidth);
    const required = rule.before + Math.max(rule.line, lines.length * rule.line) + rule.after;
    if (y + required > bottom && y > margin + 100) newPage();
    y += rule.before;
    if (block.kind === 'rule') {
      context.strokeStyle = rule.color;
      context.lineWidth = 2;
      context.beginPath();
      context.moveTo(margin, y);
      context.lineTo(width - margin, y);
      context.stroke();
      y += rule.after;
      continue;
    }
    context.font = rule.font;
    context.fillStyle = rule.color;
    if (block.kind === 'bullet') {
      context.fillStyle = '#b9523f';
      context.beginPath();
      context.arc(margin + 6, y + 10, 4, 0, Math.PI * 2);
      context.fill();
      context.fillStyle = rule.color;
    }
    lines.forEach((line, index) => {
      if (y + rule.line > bottom) {
        newPage();
        context.font = rule.font;
        context.fillStyle = rule.color;
        // A continued bullet gets a quiet continuation indent rather than a
        // second marker that would incorrectly look like a new list item.
        if (block.kind === 'bullet' && index > 0) y += 4;
      }
      context.fillText(line, margin + inset, y);
      y += rule.line;
    });
    y += rule.after;
  }

  pages.forEach((page, index) => {
    const ctx = page.getContext('2d')!;
    ctx.font = '400 15px system-ui, sans-serif';
    ctx.fillStyle = '#8b817b';
    ctx.textAlign = 'left';
    ctx.fillText(`Generated by Siddha · ${generated}`, margin, height - 48);
    ctx.textAlign = 'right';
    ctx.fillText(`${index + 1} / ${pages.length}`, width - margin, height - 48);
  });
  return pages;
}

export function askReportPdf(input: AskReportInput): Blob {
  if (typeof document === 'undefined') throw new Error('PDF export requires a browser.');
  const images = canvasPages(input).map(canvas => ({
    width: canvas.width,
    height: canvas.height,
    data: dataUrlBytes(canvas.toDataURL('image/jpeg', 0.9)),
  }));
  const objectCount = 2 + images.length * 3;
  const objects = new Map<number, Uint8Array>();
  const pageIds = images.map((_, index) => 3 + index * 3);
  objects.set(1, bytes('<< /Type /Catalog /Pages 2 0 R >>'));
  objects.set(2, bytes(`<< /Type /Pages /Count ${images.length} /Kids [${pageIds.map(id => `${id} 0 R`).join(' ')}] >>`));

  images.forEach((image, index) => {
    const pageId = 3 + index * 3;
    const contentId = pageId + 1;
    const imageId = pageId + 2;
    const imageName = `Im${index + 1}`;
    objects.set(pageId, bytes(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /${imageName} ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`));
    const drawing = bytes(`q\n595 0 0 842 0 0 cm\n/${imageName} Do\nQ\n`);
    objects.set(contentId, joinBytes([bytes(`<< /Length ${drawing.length} >>\nstream\n`), drawing, bytes('endstream')]));
    objects.set(imageId, joinBytes([
      bytes(`<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.data.length} >>\nstream\n`),
      image.data,
      bytes('\nendstream'),
    ]));
  });

  const parts: Uint8Array[] = [bytes('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n')];
  const offsets = new Array<number>(objectCount + 1).fill(0);
  let offset = parts[0].length;
  for (let id = 1; id <= objectCount; id++) {
    const object = objects.get(id)!;
    const prefix = bytes(`${id} 0 obj\n`);
    const suffix = bytes('\nendobj\n');
    offsets[id] = offset;
    parts.push(prefix, object, suffix);
    offset += prefix.length + object.length + suffix.length;
  }
  const xrefOffset = offset;
  let xref = `xref\n0 ${objectCount + 1}\n0000000000 65535 f \n`;
  for (let id = 1; id <= objectCount; id++) xref += `${String(offsets[id]).padStart(10, '0')} 00000 n \n`;
  xref += `trailer\n<< /Size ${objectCount + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  parts.push(bytes(xref));
  const assembled = joinBytes(parts);
  // Copy into a browser-owned ArrayBuffer so TypeScript cannot widen the
  // backing store to SharedArrayBuffer, which BlobPart deliberately rejects.
  const output = new Uint8Array(assembled.length);
  output.set(assembled);
  return new Blob([output.buffer], { type: 'application/pdf' });
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
