import { StructuredReading } from './models';
import { TextRun, cleanPlainText, paragraphRuns } from './answer-text';

export interface AskReportInput {
  profileName: string;
  question: string;
  domain: string | null;
  intent: string | null;
  createdAt: string | null;
  contextUsed: string[];
  evidenceRefs: string[];
  profileContextRevision: number;
  profileContextAsOf: string | null;
  reading: StructuredReading | null;
  fallbackContent: string;
}

interface ReportBlock {
  kind: 'title' | 'subtitle' | 'heading' | 'body' | 'bullet' | 'source' | 'rule';
  text?: string;
}

// `askReportText` (the plain-text/clipboard export) has no rendering surface
// for emphasis, so it keeps flattening `**bold**` markers the way this file
// always has — `cleanPlainText` (answer-text.ts) is that same behaviour,
// now shared with the streamed UI instead of duplicated here. The PDF path
// below deliberately does NOT use this for body/bullet text — see
// `reportBlocks()`.
const clean = cleanPlainText;

function label(value: string | null): string {
  return clean(value ?? '')
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, letter => letter.toUpperCase());
}

function sourceLabel(source: StructuredReading['technical_basis'][number]['source']): string {
  if (!source) return 'Context Engine';
  if (typeof source === 'string') return label(source);
  return [source.key, source.ref_id, source.chunk_id, source.section, source.location]
    .filter(Boolean)
    .map(value => label(String(value)))
    .join(' · ') || 'Context Engine';
}

export function askReportText(input: AskReportInput): string {
  const reading = input.reading;
  if (!reading) return clean(input.fallbackContent);
  const generated = input.createdAt ? new Date(input.createdAt).toLocaleString() : new Date().toLocaleString();

  const lines: string[] = [
    `Profile: ${clean(input.profileName) || 'Selected profile'}`,
    'SIDDHA · Your way of life guide',
    '',
    `Question: ${clean(input.question)}`,
    `Domain: ${label(input.domain) || 'Guidance'}`,
    ...(input.intent ? [`Intent: ${label(input.intent)}`] : []),
    `Confidence: ${label(reading.confidence)}`,
    '',
    'ACKNOWLEDGMENT',
    clean(reading.acknowledgment),
  ];

  lines.push('', 'INTERPRETATION', clean(reading.interpretation));
  lines.push('', 'SUMMARY AND ASSURANCE', clean(reading.summary_and_assurance));

  if (reading.guidance.practical_actions.length) {
    lines.push('', 'PRACTICAL ACTIONS');
    reading.guidance.practical_actions.forEach((action, index) => lines.push(`${index + 1}. ${clean(action)}`));
  }
  if (reading.guidance.remedies.length) {
    lines.push('', 'TRADITIONAL SUPPORTS');
    reading.guidance.remedies.forEach(remedy => {
      lines.push(`• ${clean(remedy.practice)}`);
      if (remedy.note) lines.push(`  ${clean(remedy.note)}`);
    });
  }
  if (reading.technical_basis.length) {
    lines.push('', 'TECHNICAL BASIS');
    for (const item of reading.technical_basis) {
      lines.push(`• ${clean(item.factor)}: ${clean(item.reading)}`);
      lines.push(`  Source: ${sourceLabel(item.source)}`);
    }
  }

  const provenance = [
    ...(input.contextUsed.length ? [`Context used: ${input.contextUsed.map(label).join(', ')}`] : []),
    ...(input.evidenceRefs.length ? [`Evidence references: ${input.evidenceRefs.join(', ')}`] : []),
    ...(input.profileContextRevision > 0
      ? [`Saved profile context: revision ${input.profileContextRevision}${input.profileContextAsOf ? ` as of ${input.profileContextAsOf}` : ''}`]
      : []),
  ];
  if (provenance.length) lines.push('', 'PROVENANCE', ...provenance);

  lines.push(
    '',
    'Siddha offers reflective Vedic astrology guidance. It does not replace medical, legal, financial, or other qualified professional advice.',
    '',
    `Generated by Siddha · ${generated}`,
  );
  return lines.filter((line, index) => line || lines[index - 1] !== '').join('\n').trim();
}

// `body` and `bullet` blocks below deliberately carry RAW model text —
// `**bold**`/`__bold__` markers intact, headers/bullet-dashes/whitespace
// NOT yet normalized. That normalization (and the bold-preserving run
// split) happens once, at draw time, in `wrapRichText` — this is what
// lets a Balanced-voice side-heading ("**Career Trajectory:** ...",
// allowed by _REGISTER_BALANCED's own prompt) actually render bold in the
// PDF instead of being silently flattened the way `askReportText`'s plain
// export still correctly flattens it for clipboard/TTS contexts.
function reportBlocks(input: AskReportInput): ReportBlock[] {
  const reading = input.reading;
  if (!reading) return [
    { kind: 'body', text: input.fallbackContent || '' },
  ];

  const blocks: ReportBlock[] = [
    { kind: 'source', text: `${label(input.domain) || 'Guidance'} · ${label(input.intent) || 'General'} · ${label(reading.confidence)} confidence` },
    { kind: 'heading', text: 'Acknowledgment' },
    { kind: 'body', text: reading.acknowledgment || '' },
    { kind: 'heading', text: 'Interpretation' },
    { kind: 'body', text: reading.interpretation || '' },
    { kind: 'heading', text: 'Summary and Assurance' },
    { kind: 'body', text: reading.summary_and_assurance || '' },
  ];
  if (reading.guidance.practical_actions.length) {
    blocks.push({ kind: 'heading', text: 'Practical Actions' });
    reading.guidance.practical_actions.forEach((action, index) => blocks.push({ kind: 'bullet', text: `${index + 1}. ${action}` }));
  }
  if (reading.guidance.remedies.length) {
    blocks.push({ kind: 'heading', text: 'Traditional Supports' });
    reading.guidance.remedies.forEach(remedy => blocks.push({ kind: 'bullet', text: `${remedy.practice}${remedy.note ? ` — ${remedy.note}` : ''}` }));
  }
  if (reading.technical_basis.length) {
    blocks.push({ kind: 'heading', text: 'Technical Basis' });
    reading.technical_basis.forEach(item => {
      blocks.push({ kind: 'bullet', text: `${item.factor}: ${item.reading}` });
      blocks.push({ kind: 'source', text: `Source: ${sourceLabel(item.source)}` });
    });
  }
  const provenance = [
    input.contextUsed.length ? `Context: ${input.contextUsed.map(label).join(', ')}` : '',
    input.evidenceRefs.length ? `Evidence: ${input.evidenceRefs.join(', ')}` : '',
    input.profileContextRevision > 0 ? `Profile context revision ${input.profileContextRevision}${input.profileContextAsOf ? ` as of ${input.profileContextAsOf}` : ''}` : '',
  ].filter(Boolean);
  if (provenance.length) {
    blocks.push({ kind: 'heading', text: 'Provenance' });
    provenance.forEach(value => blocks.push({ kind: 'source', text: value }));
  }
  blocks.push(
    { kind: 'rule' },
    { kind: 'source', text: 'Reflective guidance only. Siddha does not replace qualified medical, legal, financial, or other professional advice.' },
  );
  return blocks;
}

// Georgia does not exist on Android at all, and `system-ui` resolves to a
// different actual typeface on every platform (Roboto on Android, San
// Francisco on iOS, whatever the desktop OS ships) — since this PDF is
// built by rasterizing a <canvas>, not by embedding real PDF text/fonts,
// whichever face is ACTUALLY installed on the device generating it is what
// gets permanently baked into the image. Mixing two font stacks that were
// each already platform-dependent compounded the problem into visible,
// unpredictable inconsistency: the same report could render with a
// completely different heading/body contrast on every device, or with no
// contrast at all where a fallback happened to collapse both onto the same
// glyphs. Using the app's own real font (`--as-font-body`/`--as-font-display`
// in styles.scss, both 'Inter') for every text kind here fixes the
// platform-dependence at the source: the hierarchy becomes weight/size/
// color only, exactly how the live streamed answer already differentiates
// a side-heading from body prose (see `.side-heading` in
// ask-answer.component.scss).
const REPORT_FONT_FAMILY = "'Inter', system-ui, sans-serif";

function reportFont(weight: number, size: number): string {
  return `${weight} ${size}px ${REPORT_FONT_FAMILY}`;
}

/** Canvas text does not reflow once a webfont finishes loading the way
 * ordinary DOM text does — if Inter has not finished loading when
 * `fillText` runs, whatever fallback was active at that instant is what
 * gets rasterized into the image, permanently. `font` strings alone only
 * declare a preference; this is what actually waits for it. Best-effort:
 * a blocked or failed load still produces a real PDF, just with the
 * platform's own default sans-serif baked in instead of Inter — still
 * internally consistent, since every kind shares the one declared family. */
async function ensureReportFontReady(): Promise<void> {
  if (typeof document === 'undefined' || !('fonts' in document)) return;
  try {
    await Promise.all([400, 500, 600, 700].map(weight => document.fonts.load(reportFont(weight, 16))));
    await document.fonts.ready;
  } catch {
    // Ignored — see comment above.
  }
}

type Token = TextRun;
interface DrawLine {
  tokens: Token[];
  /** True for a line that opens a new paragraph (not the block's first) —
   * the draw loop adds a little extra space above it, the canvas
   * equivalent of `.reading-paragraph + .reading-paragraph`'s margin in
   * the live streamed answer. Interpretation's real paragraph breaks were
   * previously collapsed into a single run of same-height lines with no
   * visual separation at all. */
  newParagraph: boolean;
}

function tokensFromRuns(runs: TextRun[]): Token[] {
  const tokens: Token[] = [];
  for (const run of runs) {
    for (const word of run.text.split(/\s+/).filter(Boolean)) tokens.push({ text: word, bold: run.bold });
  }
  return tokens;
}

/** Word-wraps RAW model text (bold markers intact, headers/bullets not yet
 * normalized — `paragraphRuns` does both) into lines ready to draw, each
 * token individually measured against the weight it will actually be
 * drawn in. This is the one place a `**bold**` side-heading in
 * `interpretation`/`acknowledgment`/a bullet's text actually becomes a
 * highlighted run instead of being silently discarded. */
function wrapRichText(
  context: CanvasRenderingContext2D,
  rawText: string,
  maxWidth: number,
  normalFont: string,
  boldFont: string,
): DrawLine[] {
  const paragraphs = paragraphRuns(rawText);
  const drawLines: DrawLine[] = [];
  context.font = normalFont;
  const spaceWidth = context.measureText(' ').width;
  paragraphs.forEach((runs, paragraphIndex) => {
    const words = tokensFromRuns(runs);
    let line: Token[] = [];
    let lineWidth = 0;
    let isFirstLineOfParagraph = true;
    for (const word of words) {
      context.font = word.bold ? boldFont : normalFont;
      const wordWidth = context.measureText(word.text).width;
      const extra = line.length ? spaceWidth + wordWidth : wordWidth;
      if (line.length && lineWidth + extra > maxWidth) {
        drawLines.push({ tokens: line, newParagraph: isFirstLineOfParagraph && paragraphIndex > 0 });
        isFirstLineOfParagraph = false;
        line = [word];
        lineWidth = wordWidth;
      } else {
        line.push(word);
        lineWidth += extra;
      }
    }
    if (line.length) drawLines.push({ tokens: line, newParagraph: isFirstLineOfParagraph && paragraphIndex > 0 });
  });
  return drawLines;
}

/** Draws one wrapped line left-to-right, switching font/color per token so
 * a bold side-heading run and the plain prose beside it render inline on
 * the same line. Returns the x position drawing stopped at (unused today,
 * kept because a caller measuring trailing space is a natural next need). */
function drawRichLine(
  context: CanvasRenderingContext2D,
  line: DrawLine,
  x: number,
  y: number,
  normalFont: string,
  boldFont: string,
  normalColor: string,
  boldColor: string,
): void {
  context.font = normalFont;
  const spaceWidth = context.measureText(' ').width;
  let cursorX = x;
  line.tokens.forEach(token => {
    context.font = token.bold ? boldFont : normalFont;
    context.fillStyle = token.bold ? boldColor : normalColor;
    context.fillText(token.text, cursorX, y);
    cursorX += context.measureText(token.text).width + spaceWidth;
  });
}

function bytes(value: string): Uint8Array {
  return new TextEncoder().encode(value);
}

function joinBytes(parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const joined = new Uint8Array(total);
  let offset = 0;
  parts.forEach(part => { joined.set(part, offset); offset += part.length; });
  return joined;
}

function dataUrlBytes(dataUrl: string): Uint8Array {
  const binary = atob(dataUrl.split(',')[1] ?? '');
  return Uint8Array.from(binary, char => char.charCodeAt(0));
}

// The canvas equivalent of `.reading-paragraph + .reading-paragraph`'s
// margin in ask-answer.component.scss — a real paragraph in Interpretation
// previously produced no visible gap at all, just more same-height lines.
const PARAGRAPH_GAP = 12;

async function canvasPages(input: AskReportInput): Promise<HTMLCanvasElement[]> {
  await ensureReportFontReady();
  const width = 1240;
  const height = 1754;
  const margin = 104;
  const bottom = height - 124;
  const profileName = clean(input.profileName) || 'Selected profile';
  const generated = input.createdAt ? new Date(input.createdAt).toLocaleString() : new Date().toLocaleString();
  const pages: HTMLCanvasElement[] = [];
  let canvas!: HTMLCanvasElement;
  let context!: CanvasRenderingContext2D;
  let y = margin;

  const newPage = () => {
    canvas = document.createElement('canvas');
    canvas.width = width;
    canvas.height = height;
    context = canvas.getContext('2d')!;
    context.fillStyle = '#fffdf9';
    context.fillRect(0, 0, width, height);
    context.font = reportFont(600, 20);
    context.fillStyle = '#332823';
    context.textAlign = 'left';
    context.fillText(profileName, margin, 65);
    // Distinguished from the profile name by weight and accent color alone,
    // not by a second, platform-dependent typeface — see REPORT_FONT_FAMILY.
    context.font = reportFont(700, 22);
    context.fillStyle = '#8f3f30';
    context.textAlign = 'right';
    context.fillText('SIDDHA', width - margin, 65);
    context.strokeStyle = '#dfcec4';
    context.lineWidth = 2;
    context.beginPath();
    context.moveTo(margin, 92);
    context.lineTo(width - margin, 92);
    context.stroke();
    context.textAlign = 'left';
    pages.push(canvas);
    y = 132;
  };
  newPage();

  const style = (kind: ReportBlock['kind']) => {
    const rules = {
      title: { font: reportFont(700, 52), boldFont: reportFont(700, 52), color: '#6f2f24', boldColor: '#6f2f24', line: 66, before: 0, after: 4 },
      subtitle: { font: reportFont(500, 24), boldFont: reportFont(700, 24), color: '#6e625b', boldColor: '#6e625b', line: 34, before: 0, after: 18 },
      heading: { font: reportFont(700, 22), boldFont: reportFont(700, 22), color: '#8f3f30', boldColor: '#8f3f30', line: 31, before: 30, after: 8 },
      // `boldColor` gives a `**bold**` side-heading the same accent as a
      // real heading — the point of the highlight, not just a weight bump.
      body: { font: reportFont(400, 22), boldFont: reportFont(700, 22), color: '#241d19', boldColor: '#8f3f30', line: 34, before: 0, after: 15 },
      bullet: { font: reportFont(400, 21), boldFont: reportFont(700, 21), color: '#241d19', boldColor: '#8f3f30', line: 32, before: 3, after: 7 },
      source: { font: reportFont(400, 16), boldFont: reportFont(700, 16), color: '#756b65', boldColor: '#8f3f30', line: 25, before: 0, after: 8 },
      rule: { font: '', boldFont: '', color: '#d8c4b9', boldColor: '#d8c4b9', line: 1, before: 8, after: 14 },
    };
    return rules[kind];
  };

  const blocks = reportBlocks(input);
  for (let blockIndex = 0; blockIndex < blocks.length; blockIndex++) {
    const block = blocks[blockIndex];
    const rule = style(block.kind);
    const inset = block.kind === 'bullet' ? 28 : 0;
    const contentWidth = width - margin * 2 - inset;
    const lines = block.kind === 'rule' ? [] : wrapRichText(context, block.text ?? '', contentWidth, rule.font, rule.boldFont);
    const required = rule.before + Math.max(rule.line, lines.length * rule.line) + rule.after;
    let keepWithNext = 0;
    if (block.kind === 'heading') {
      const next = blocks[blockIndex + 1];
      if (next && next.kind !== 'heading' && next.kind !== 'rule') {
        const nextRule = style(next.kind);
        const nextInset = next.kind === 'bullet' ? 28 : 0;
        const nextLines = wrapRichText(context, next.text ?? '', width - margin * 2 - nextInset, nextRule.font, nextRule.boldFont);
        keepWithNext = nextRule.before + Math.min(3, Math.max(1, nextLines.length)) * nextRule.line;
      }
    }
    // Long prose should consume the space that remains on this page, not jump
    // wholesale to a fresh page. Start a non-heading block on a fresh page only
    // when fewer than three opening lines would fit.
    const openingLines = block.kind === 'rule' ? rule.line : Math.min(3, Math.max(1, lines.length)) * rule.line;
    const minimumUsefulSpace = rule.before + openingLines + rule.after;
    const shouldBreak = block.kind === 'heading'
      ? y + required + keepWithNext > bottom
      : y + minimumUsefulSpace > bottom;
    if (shouldBreak && y > margin + 100) {
      newPage();
    }
    y += rule.before;
    if (block.kind === 'rule') {
      context.strokeStyle = rule.color;
      context.lineWidth = 2;
      context.beginPath();
      context.moveTo(margin, y);
      context.lineTo(width - margin, y);
      context.stroke();
      y += rule.after;
      continue;
    }
    if (block.kind === 'bullet') {
      context.fillStyle = '#b9523f';
      context.beginPath();
      context.arc(margin + 6, y + 10, 4, 0, Math.PI * 2);
      context.fill();
    }
    lines.forEach((line, index) => {
      if (y + rule.line > bottom) {
        newPage();
        // A continued bullet gets a quiet continuation indent rather than a
        // second marker that would incorrectly look like a new list item.
        if (block.kind === 'bullet' && index > 0) y += 4;
      }
      if (line.newParagraph) y += PARAGRAPH_GAP;
      drawRichLine(context, line, margin + inset, y, rule.font, rule.boldFont, rule.color, rule.boldColor);
      y += rule.line;
    });
    y += rule.after;
  }

  pages.forEach((page, index) => {
    const ctx = page.getContext('2d')!;
    ctx.font = reportFont(400, 15);
    ctx.fillStyle = '#8b817b';
    ctx.textAlign = 'left';
    ctx.fillText(`Generated by Siddha · ${generated}`, margin, height - 48);
    ctx.textAlign = 'right';
    ctx.fillText(`${index + 1} / ${pages.length}`, width - margin, height - 48);
  });
  return pages;
}

export async function askReportPdf(input: AskReportInput): Promise<Blob> {
  if (typeof document === 'undefined') throw new Error('PDF export requires a browser.');
  const images = (await canvasPages(input)).map(canvas => ({
    width: canvas.width,
    height: canvas.height,
    data: dataUrlBytes(canvas.toDataURL('image/jpeg', 0.9)),
  }));
  const objectCount = 2 + images.length * 3;
  const objects = new Map<number, Uint8Array>();
  const pageIds = images.map((_, index) => 3 + index * 3);
  objects.set(1, bytes('<< /Type /Catalog /Pages 2 0 R >>'));
  objects.set(2, bytes(`<< /Type /Pages /Count ${images.length} /Kids [${pageIds.map(id => `${id} 0 R`).join(' ')}] >>`));

  images.forEach((image, index) => {
    const pageId = 3 + index * 3;
    const contentId = pageId + 1;
    const imageId = pageId + 2;
    const imageName = `Im${index + 1}`;
    objects.set(pageId, bytes(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /${imageName} ${imageId} 0 R >> >> /Contents ${contentId} 0 R >>`));
    const drawing = bytes(`q\n595 0 0 842 0 0 cm\n/${imageName} Do\nQ\n`);
    objects.set(contentId, joinBytes([bytes(`<< /Length ${drawing.length} >>\nstream\n`), drawing, bytes('endstream')]));
    objects.set(imageId, joinBytes([
      bytes(`<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.data.length} >>\nstream\n`),
      image.data,
      bytes('\nendstream'),
    ]));
  });

  const parts: Uint8Array[] = [bytes('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n')];
  const offsets = new Array<number>(objectCount + 1).fill(0);
  let offset = parts[0].length;
  for (let id = 1; id <= objectCount; id++) {
    const object = objects.get(id)!;
    const prefix = bytes(`${id} 0 obj\n`);
    const suffix = bytes('\nendobj\n');
    offsets[id] = offset;
    parts.push(prefix, object, suffix);
    offset += prefix.length + object.length + suffix.length;
  }
  const xrefOffset = offset;
  let xref = `xref\n0 ${objectCount + 1}\n0000000000 65535 f \n`;
  for (let id = 1; id <= objectCount; id++) xref += `${String(offsets[id]).padStart(10, '0')} 00000 n \n`;
  xref += `trailer\n<< /Size ${objectCount + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  parts.push(bytes(xref));
  const assembled = joinBytes(parts);
  // Copy into a browser-owned ArrayBuffer so TypeScript cannot widen the
  // backing store to SharedArrayBuffer, which BlobPart deliberately rejects.
  const output = new Uint8Array(assembled.length);
  output.set(assembled);
  return new Blob([output.buffer], { type: 'application/pdf' });
}

export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  // Standards-compliant browsers honour `download`; embedded browsers that
  // suppress it can still open the PDF in a separate preview surface.
  anchor.target = '_blank';
  anchor.rel = 'noopener';
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();

  // WebViews and embedded browsers may consume the object URL after the
  // synthetic click task completes. Revoking it immediately makes the click
  // appear successful while silently cancelling the actual download.
  setTimeout(() => URL.revokeObjectURL(url), 30_000);
}
