import {
  ApplicationConfig,
  inject,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
  provideAppInitializer,
  provideZoneChangeDetection,
} from '@angular/core';
import { provideRouter, RouteReuseStrategy } from '@angular/router';
import { MobileRouteReuseStrategy } from './core/mobile-route-reuse-strategy';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { providePrimeNG } from 'primeng/config';
import { ConfirmationService, MessageService } from 'primeng/api';
import {
  AlertTriangle,
  Activity,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeAlert,
  BookCheck,
  BookOpen,
  BookOpenCheck,
  Bot,
  Boxes,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ChartNoAxesCombined,
  Check,
  CircleAlert,
  CircleCheck,
  CircleX,
  ClipboardCheck,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cloud,
  CloudDownload,
  Compass,
  Database,
  Flame,
  FlaskConical,
  Gem,
  Globe,
  Grid3x3,
  HeartHandshake,
  History,
  Home,
  Info,
  LayoutDashboard,
  LayoutGrid,
  Library,
  List,
  LogOut,
  LucideAngularModule,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquareText,
  Moon,
  MoonStar,
  NotebookPen,
  NotebookTabs,
  Orbit,
  Pencil,
  Plus,
  Radar,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  ServerCog,
  Settings,
  Send,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  SunMoon,
  Sunrise,
  Sunset,
  Table2,
  TriangleAlert,
  Trash2,
  User,
  UserRound,
  UserRoundCheck,
  UserX,
  Users,
  Upload,
  X,
} from 'lucide-angular';

import { routes } from './app.routes';
import { CelestialPreset } from './theme';
import { ResourceCacheService } from './core/resource-cache.service';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideAppInitializer(() => inject(ResourceCacheService).initialize()),
    provideZoneChangeDetection({ eventCoalescing: true }),
    { provide: RouteReuseStrategy, useClass: MobileRouteReuseStrategy },
    provideRouter(routes),
    provideHttpClient(withFetch()),
    provideAnimationsAsync(),
    providePrimeNG({
      theme: {
        preset: CelestialPreset,
        options: {
          darkModeSelector: '.app-dark',
        },
      },
    }),
    MessageService,
    ConfirmationService,
    importProvidersFrom(
      LucideAngularModule.pick({
        AlertTriangle,
        Activity,
        ArrowLeft,
        ArrowRight,
        Award,
        BadgeAlert,
        BookCheck,
        BookOpen,
        BookOpenCheck,
        Bot,
        Boxes,
        CalendarClock,
        CalendarDays,
        CalendarRange,
        ChartNoAxesCombined,
        Check,
        CircleAlert,
        CircleCheck,
        CircleX,
        ClipboardCheck,
        ChevronLeft,
        ChevronRight,
        Clock,
        Cloud,
        CloudDownload,
        Compass,
        Database,
        Flame,
        FlaskConical,
        Gem,
        Globe,
        Grid3x3,
        HeartHandshake,
        History,
        Home,
        Info,
        LayoutDashboard,
        LayoutGrid,
        Library,
        List,
        LogOut,
        Mail,
        MapPin,
        MessageCircle,
        MessageSquareText,
        Moon,
        MoonStar,
        NotebookPen,
        NotebookTabs,
        Orbit,
        Pencil,
        Plus,
        Radar,
        RefreshCw,
        RotateCcw,
        Save,
        Search,
        ServerCog,
        Settings,
        Send,
        ShieldCheck,
        Sparkles,
        Star,
        Sun,
        SunMoon,
        Sunrise,
        Sunset,
        Table2,
        TriangleAlert,
        Trash2,
        User,
        UserRound,
        UserRoundCheck,
        UserX,
        Users,
        Upload,
        X,
      }),
    ),
  ],
};
