import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
  provideZoneChangeDetection,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withFetch } from '@angular/common/http';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { providePrimeNG } from 'primeng/config';
import { ConfirmationService, MessageService } from 'primeng/api';
import {
  AlertTriangle,
  Activity,
  ArrowRight,
  Award,
  BadgeAlert,
  BookCheck,
  BookOpen,
  BookOpenCheck,
  Bot,
  Boxes,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  ChartNoAxesCombined,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cloud,
  CloudDownload,
  Compass,
  Database,
  Flame,
  Gem,
  Globe,
  Grid3x3,
  HeartHandshake,
  Home,
  Info,
  LayoutDashboard,
  LayoutGrid,
  List,
  LogOut,
  LucideAngularModule,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquareText,
  Moon,
  MoonStar,
  NotebookPen,
  NotebookTabs,
  Orbit,
  Pencil,
  Plus,
  Radar,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Settings,
  Send,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  SunMoon,
  Sunrise,
  Sunset,
  Table2,
  Trash2,
  User,
  UserRound,
  UserRoundCheck,
  Users,
  X,
} from 'lucide-angular';

import { routes } from './app.routes';
import { CelestialPreset } from './theme';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideHttpClient(withFetch()),
    provideAnimationsAsync(),
    providePrimeNG({
      theme: {
        preset: CelestialPreset,
        options: {
          darkModeSelector: '.app-dark',
        },
      },
    }),
    MessageService,
    ConfirmationService,
    importProvidersFrom(
      LucideAngularModule.pick({
        AlertTriangle,
        Activity,
        ArrowRight,
        Award,
        BadgeAlert,
        BookCheck,
        BookOpen,
        BookOpenCheck,
        Bot,
        Boxes,
        CalendarClock,
        CalendarDays,
        CalendarRange,
        ChartNoAxesCombined,
        Check,
        ChevronLeft,
        ChevronRight,
        Clock,
        Cloud,
        CloudDownload,
        Compass,
        Database,
        Flame,
        Gem,
        Globe,
        Grid3x3,
        HeartHandshake,
        Home,
        Info,
        LayoutDashboard,
        LayoutGrid,
        List,
        LogOut,
        Mail,
        MapPin,
        MessageCircle,
        MessageSquareText,
        Moon,
        MoonStar,
        NotebookPen,
        NotebookTabs,
        Orbit,
        Pencil,
        Plus,
        Radar,
        RefreshCw,
        RotateCcw,
        Save,
        Search,
        Settings,
        Send,
        ShieldCheck,
        Sparkles,
        Star,
        Sun,
        SunMoon,
        Sunrise,
        Sunset,
        Table2,
        Trash2,
        User,
        UserRound,
        UserRoundCheck,
        Users,
        X,
      }),
    ),
  ],
};
